CREATE TABLE breweries(
   ID              INTEGER  NOT NULL PRIMARY KEY 
  ,Name            VARCHAR(28) NOT NULL
  ,Beer_Category   VARCHAR(11) NOT NULL
  ,Type_of_Beer    VARCHAR(15) NOT NULL
  ,Brewpub         VARCHAR(3) NOT NULL
  ,Address         VARCHAR(76) NOT NULL
  ,Closest_Station VARCHAR(35) NOT NULL
  ,Latitude        NUMERIC(9,6) NOT NULL
  ,Longitude       NUMERIC(9,6) NOT NULL
  ,Url             VARCHAR(65) NOT NULL
);
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (1,'40ft','Lager','Lager','Yes','The Bootyard, Abbott St, E8 3DP','Dalston Junction, Dalston Kingsland',51.547096,-0.074446,'http://craftbeerlondon.com/breweries/40ft');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (2,'Aeronaut','Ale','IPA','Yes','264 Acton High St, W3 9BH','Acton Town',51.508485,-0.275324,'http://craftbeerlondon.com/breweries/Aeronaut');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (3,'Anspach and Hobday','StoutPorter','Porter','Yes','118 Druid Street, London, SE1 2HH','Bermondsey',51.498705,-0.073437,'http://craftbeerlondon.com/breweries/Anspach-and-Hobday');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (4,'Barnet','Ale','IPA','Yes','92 Wood Street, Barnet, EN5 4HY','High Barnet',51.653137,-0.206574,'http://craftbeerlondon.com/breweries/Barnet');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (5,'BeavertownBrewing','Ale','IPA','Yes','Unit 17 &18, Lockwood Industrial Park, Mill Mead Rd, Tottenham Hale, N17 9QP','Tottenham Hale',51.590851,-0.056757,'http://craftbeerlondon.com/breweries/Beavertown-Brewing');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (6,'Belleville','Ale','IPA','No','Unit 36, Jaggard Way, SW12 8SG','Wandsworth Common',51.445795,-0.16235,'http://craftbeerlondon.com/breweries/Belleville');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (7,'Bexley Brewery','Ale','Pale Ale','Yes','18, Manford Industrial Estate, Manor Road, Erith, DA8 2AJ','Erith Rail',51.477951,0.195547,'http://craftbeerlondon.com/breweries/bexley-brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (8,'Big Smoke Brew Co','Special','Other','Yes','87 Maple Road, Surrey, KT6 4AW','Surbiton',51.395162,-0.307724,'http://craftbeerlondon.com/breweries/big-smoke-brew-co');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (9,'Brew By Numbers','Ale','Berliner Weisse','Yes','79, Enid St, SE16 3RA','Bermondsey',51.497492,-0.072014,'http://craftbeerlondon.com/breweries/brew-by-numbers');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (10,'Brick Brewery','Lager','Pilsner','Yes','Arch 209, Blenheim Grove, Peckham Rye, SE15 4QL','Peckham Rye',51.469595,-0.069607,'http://craftbeerlondon.com/breweries/Brick-Brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (11,'Brixton','Ale','IPA','No','Arch 547, Brixton Station Road, SW9 8PF','Brixton',51.463506,-0.109336,'http://craftbeerlondon.com/breweries/Brixton');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (12,'Brockley Brewery','Ale','Pale Ale','No','31 Harcourt Road, SE4 2AJ','Briockley',51.462062,-0.0362,'http://craftbeerlondon.com/breweries/Brockley');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (13,'Brodie Aos','Ale','IPA','Yes','816A High Road Leyton, London, E10 6AE','Leyton Midland Road',51.574765,-0.011458,'http://craftbeerlondon.com/breweries/Brodie-s');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (14,'Bullfinch','Ale','IPA','Yes','Arch 886, Rosendale Rd, London SE24 9EH','Bermondsey',51.448093,-0.101617,'http://craftbeerlondon.com/breweries/Bullfinch');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (15,'By the Horns','Ale','Red Ale','Yes','25 Summerstown, Wandsworth, SW17 OBQ','Wimbledon Park',51.432506,-0.184729,'http://craftbeerlondon.com/breweries/By-the-Horns');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (16,'Camden Town Brewery','Lager','Lager','Yes','55-59 Wilkin Street Mews, NW5 3NN','Kentish Town Rest',51.547057,-0.146823,'http://craftbeerlondon.com/breweries/camden-town-brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (17,'Canopy Beer Co','Ale','IPA','Yes','Arch 1127, Bath Factory Estate, 41 Norwood Rd, Herne Hill, SE24 9AJ','Herne Hill',51.451668,-0.100794,'http://craftbeerlondon.com/breweries/canopy-beer-co');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (18,'Clarkshaws','Ale','IPA','Yes','Arch 497, Ridgway Road, Brixton, SW9 7EX','Lougborough Junction, Brixton',51.465809,-0.103416,'http://craftbeerlondon.com/breweries/clarkshaws');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (19,'Crate','Ale','IPA','Yes','Queen''s Yard, Hackney Wick, E9 5EN','Hackney Wick',51.543055,-0.023052,'http://craftbeerlondon.com/breweries/crate-brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (20,'The Cronx','Ale','Pale Ale','No','Unit 6, Vulcan Business Centre, Croydon, CR0 9UG','West Wickham',51.343982,-0.003481,'http://craftbeerlondon.com/breweries/cronx-brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (21,'Dragonfly','StoutPorter','Stout','Yes','183, High Street, W3 9DJ','Acton Central',51.507277,-0.271792,'http://craftbeerlondon.com/breweries/Dragonfly');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (22,'Earl''s','Special','Other','Yes','25 Danbury Street, N1 8LE','Angle',51.533834,-0.099766,'http://craftbeerlondon.com/breweries/Earl-s');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (23,'Earth Ale','StoutPorter','Stout','No','Zennor Road, Balham, SW12 0PS','Balham',51.445258,-0.14493,'http://craftbeerlondon.com/breweries/earth-ale');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (24,'East London Brewing','Ale','Pale Ale','No','Unit 45, Fairways Business Centre , Lammas Road, E10 7QB','Clapton',51.564711,-0.033888,'http://craftbeerlondon.com/breweries/East-London-Brewing');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (25,'Essex Street Brewing company','Ale','Pale Ale','Yes','46 Essex Street, London WC2R 3JF','Temple',51.512971,-0.113031,'http://craftbeerlondon.com/breweries/essex-street-brewing-company');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (26,'Five Points','Ale','Pale Ale','No','3, Institute Place, E8 1JE','Hackney Central',51.548643,-0.060338,'http://craftbeerlondon.com/breweries/Five-Points');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (27,'Four Theieves','Ale','Bitter','Yes','51 Lavender Gardens, SW11 1DJ','Clapham Junction',51.464104,-0.16259,'http://craftbeerlondon.com/breweries/four-thieves');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (28,'Fourpure','StoutPorter','Stout','Yes','22, Bermondsey Trading Estate, Rotherhithe New Road, SE16 3LL','Bermondsey',51.489399,-0.055171,'http://craftbeerlondon.com/breweries/Fourpure');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (29,'Fullers','Ale','Bitter','No','The Griffin Brewery, Chiswick Lane South, W4 2QB','Stamford Brook',51.487098,-0.248234,'http://craftbeerlondon.com/breweries/Fuller-s');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (30,'Gipsy Hill Brewing Company','Ale','Amber Ale','Yes','Unit 11, Hamilton Road industrial Estate, SE27 9SF','Gipsy Hill',51.428409,-0.088617,'http://craftbeerlondon.com/breweries/Gipsy-Hill-Brewing-Company');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (31,'Hackney Brewery','Ale','Pale Ale','No','Arch 358, Laburnum Street, Hackney, London, E2 8BB','Haggerston',51.53473,-0.075809,'http://craftbeerlondon.com/breweries/Hackney-Brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (32,'Hammerton','StoutPorter','Oyster Stout','No','Unit 8 & 9 Roman Way Industrial Estate, 149 Roman Way, N7 8XH','Caledonian Road & Barnsbury',51.543064,-0.115341,'http://craftbeerlondon.com/breweries/Hammerton');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (33,'Hop Stuff','Ale','Bitter','No','7, Gunnery Terrace, Cornwallis Road, SE18 6SW','Woolwich Arsenal',51.492167,0.073906,'http://craftbeerlondon.com/breweries/hop-stuff');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (34,'Howling Hops','Special','Other','Yes','Unit 9, Queen’s Yard, E9 5EN','Hackney Wick',51.542956,-0.023137,'http://craftbeerlondon.com/breweries/howling-hops');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (35,'Islington Brewhouse kitchen','StoutPorter','Stout','Yes','Torrens St, EC1V 1NQ','Angel',51.532558,-0.105151,'http://craftbeerlondon.com/breweries/islington-brewhouse-kitchen');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (36,'Kenel Brewery','StoutPorter','Stout','Yes','Arch 11, Dockley Road, Industrial Estate, SE16 3SF','Bermondsey',51.495748,-0.068528,'http://craftbeerlondon.com/breweries/kernel-brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (37,'London Beer Factory','Ale','Blonde','Yes','160, Hamilton Road, SE27 9SF','Gipsy Hill',51.428317,-0.088478,'http://craftbeerlondon.com/breweries/London-Beer-Factory');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (38,'London Brewing','Ale','IPA','Yes','762-764 High Rd, N12 9QH','Woodside Park',51.615308,-0.176414,'http://craftbeerlondon.com/breweries/London-Brewing');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (39,'London Fields Brewery','Ale','Pale Ale','Yes','365-366, Warburton Street, E8 3RR','London Fields',51.538699,-0.058047,'http://craftbeerlondon.com/breweries/London-Fields-Brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (40,'Long arm brewing','Ale','IPA','Yes','222 South Ealing Road, Ealing W5 4RL','South Ealing',51.495557,-0.305912,'http://craftbeerlondon.com/breweries/long-arm-brewing');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (41,'Maregade','Ale','Pale Ale','Yes','315 Mare Street, Hackney, E8 1EJ','Hackney Central',51.546356,-0.055376,'http://craftbeerlondon.com/breweries/maregade');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (42,'Meantime','Ale','IPA','No','Blackwall Lane, SE10 0AR','North Greenwich',51.48953,0.008708,'http://craftbeerlondon.com/breweries/Meantime');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (43,'Moncada Bewing','Ale','Amber Ale','Yes','Unit 1, Buspace Studios, Middle Row, W10 5AT','Notting Hill Amber',51.52555,-0.211172,'http://craftbeerlondon.com/breweries/Moncada-Brewing');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (44,'Mondo','Malt','Altbier','Yes','86, Stewart''s Road, Battersea, SW8 4UG','Queenstown Road',51.474728,-0.140092,'http://craftbeerlondon.com/breweries/mondo');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (45,'Old KentRoad','Ale','Saison','No','Arches 29-30, Old Jamaica Business Estate, SE16 4AW','Bermondsey',51.497633,-0.071101,'http://craftbeerlondon.com/breweries/oldkentroad');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (46,'One MileEnd','Ale','IPA','Yes','2, Compass West Estate, 32 West Rd, N17 0XL','Whitechapel',51.606212,-0.056645,'http://craftbeerlondon.com/breweries/one-mile-end');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (47,'Orbit Beers','Malt','Altbier','Yes','Railway Arches 225 & 228, Fielding Street, SE17 3HD','Kennington',51.485138,-0.096045,'http://craftbeerlondon.com/breweries/orbit-beers');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (48,'The Park Brewery','Ale','Pale Ale','No','95, Elm Road, Kingston-upon-Thames, KT2 6HX','Kingston',51.417111,-0.293889,'http://craftbeerlondon.com/breweries/park-brewery-the');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (49,'Partizan Brewery','StoutPorter','Stout','Yes','8 Almond Road, South Bermondsey, SE16 3LR','Bermondsey',51.49132,-0.058731,'http://craftbeerlondon.com/breweries/partizan-brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (50,'Peoples Park Tavern','Ale','Bitter','Yes','360, Victoria Park Road, E9 7BT','Hackney Wick',51.539285,-0.040455,'http://craftbeerlondon.com/breweries/peoples-park-tavern');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (51,'Portobello','StoutPorter','Porter','No','Unit 6, Mitre Bridge Industrial Estate, W10 6 AU','Kensal Green',51.52435,-0.23097,'http://craftbeerlondon.com/breweries/Portobello');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (52,'Pressure Drop','Ale','Pale Ale','No','Unit 19, Bohemia Place, E8 1DU','Hackney Central',51.547383,-0.0521,'http://craftbeerlondon.com/breweries/Pressure-Drop');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (53,'Redchurch Brewery','Ale','Pale Ale','Yes','275-276, Poyser Street, E2 9RF','Bethnal Green',51.530356,-0.056893,'http://craftbeerlondon.com/breweries/redchurch-brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (54,'Redemption','Ale','Light Ale','No','16, Compass West Estate, West Rd, N17 0XL','Northumberland Park',51.606212,-0.056645,'http://craftbeerlondon.com/breweries/Redemption');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (55,'Rocky Head','Ale','Pale Ale','No','Unit 16, Glenville Mews, Kimber Road, SW18 4NJ','Southfields',51.448618,-0.19515,'http://craftbeerlondon.com/breweries/Rocky-Head');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (56,'Sambrooks','Ale','Bitter','Yes','Unit 1 & 2 Yelverton Road, Battersea, SW11 3QG','Clapham Junction',51.469952,-0.175965,'http://craftbeerlondon.com/breweries/sambrooks');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (57,'Signature Brewery','Ale','IPA','Yes','Unit 25, Leyton Business Centre, Etloe Road, E10 7BT','Leyton',51.564384,-0.022241,'http://craftbeerlondon.com/breweries/signature-brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (58,'Solvay Society','Ale','Saison','Yes','382 Essex Rd N1 3PF','Canonbury',51.544966,-0.08832,'http://craftbeerlondon.com/breweries/solvay-society');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (59,'Southwark Brewing co','Ale','Pale Ale','Yes','46 Druid Street, SE1 2EZ','Bermondsey',51.500401,-0.076449,'http://craftbeerlondon.com/breweries/southwark-brewing-co"');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (60,'Tap East','StoutPorter','Stout','Yes','7 International Square, Westfield E20 1EE','Stratford',51.544185,-0.008884,'http://craftbeerlondon.com/breweries/tapeast');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (61,'The Park Brewery','Ale','Pale Ale','No','95, Elm Road, Kingston-upon-Thames, KT2 6HX','Kingston',51.417111,-0.293889,'http://craftbeerlondon.com/breweries/park-brewery-the');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (62,'Trumans','Ale','Bitter','No','2&3, Stour Road, Hackney Wick, E3 2NT','Hackney Wick',51.539221,-0.021498,'http://craftbeerlondon.com/breweries/Truman-s');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (63,'Twickenham Fine  Ales','Ale','Bitter','No','Ryecroft Works, Edwin Road, Twickenham, TW2 6SP','Twickenham',51.445686,-0.339564,'http://craftbeerlondon.com/breweries/Twickenham-Fine-Ales');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (64,'Ubrew','Special','Other','Yes','Arches 29-30, Old Jamaica Business Estate, SE16 4AW','Bermondsey',51.497633,-0.071101,'http://craftbeerlondon.com/breweries/old-kent-road');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (65,'Weird Beard Brew Co','Ale','Pale Ale','No','Unit 5, Boston Business Park, W7 2QA','Boston Manor',51.499279,-0.338717,'http://craftbeerlondon.com/breweries/weird-beard-brew-co');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (66,'Wild Card Brewery','Ale','Ruby Ale','Yes','Unit 7, Ravenswood Industrial Estate, Shernhall Street, Wathamstow, E179HQ','Walthamstow Central',51.583957,-0.008728,'http://craftbeerlondon.com/breweries/wild-card-brewery');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (67,'Wimbledon','Ale','Pale Ale','No','Prince Georges Road, Wimbledon, SW19 2PT','Collier''s Wood',51.413411,-0.176184,'http://craftbeerlondon.com/breweries/wimbledon');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (68,'Windsor And Eton','Ale','IPA','No','Duke Street, Windsor, SL4 1SE','Windsor & Eton Central',51.483717,-0.618158,'http://craftbeerlondon.com/breweries/windsor-and-eton');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (69,'Youngs','Ale','Ale','No','Riverside House, 26 Osiers Road, Wandsworth , SW18 1NH','East Putney',51.461998,-0.198569,'http://craftbeerlondon.com/breweries/youngs');
INSERT INTO breweries(ID,Name,Beer_Category,Type_of_Beer,Brewpub,Address,Closest_Station,Latitude,Longitude,Url) VALUES (70,'Zerodegrees','Lager','Pilsner','Yes','29/31 Montpelier Vale, Blackheath, SE3 0TJ','Blackheath',51.467242,0.008209,'http://craftbeerlondon.com/breweries/zerodegrees-brewpub');
